#!/usr/bin/env python3
"""
Removes features that cannot be validated.

Each of these presented a number as evidence when the number was generated by
the tool itself. That is the one failure mode a risk-advisory tool cannot
survive in front of a client CFO, and it is worth more to delete them than to
caveat them.

1. Counterparty risk table - invented counterparty names, exposures and limit
   utilisations. Labelled "illustrative", but it sits one tab away from real
   analysis and reads as a credit system. Deleted, not caveated.

2. Backtest on synthetic outcomes - realised outcomes were derived from seeded
   random walks, and the mock was constructed such that the ensemble ranks
   near the top. The tool then cited that as "the empirical case for
   multi-model weighting". Replaced with a validation-status panel that reports
   honestly on the real score history accumulating in data/history.json and
   states what is still missing.

3. Structured-judgment model family (AHP + FMEA + Bow-Tie) - claimed a seeded
   pairwise matrix with a consistency ratio and a Delphi panel that does not
   exist, and its own disclosed limits admitted the ratings share inputs with
   the objective model. So it added no independent information while carrying
   15% of the ensemble weight and inflating apparent model agreement. Deleted
   and its weight redistributed.

4. GPD/EVT fitted to Monte-Carlo output - circular by construction: fitting an
   extreme-value distribution to the simulator's own draws recovers the
   simulator's assumptions, not the market's tails. The EVT model stays but
   now reports the scaled tail honestly and states that a real fit needs
   market return history.

5. Alpha Vantage key entry - asked the viewer to paste a personal API key into
   the browser to repair the correlation matrix. The daily pipeline computes
   real correlations now, so this is dead weight and a bad pattern besides.

6. "Probability of breach" language on an unfitted logistic - the coefficients
   were never fitted to outcomes, so it is a monotone transform of the score,
   not a probability. Kept as a ranked pressure index, relabelled everywhere.

7. A dead __placeholder JSON block.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "index.html")

VALIDATION_JS = r"""
// ---- Validation status ----------------------------------------------------
// Replaces the synthetic-outcome backtest. Reports only what the accumulated
// real score history in data/history.json can support, and says plainly what
// is still missing. No synthetic outcomes, no manufactured metrics.
const VALID_MIN_WEEKS = 12;
function validationView(){
  const H = (typeof HDATA !== 'undefined' && HDATA && HDATA.dates) ? HDATA : null;
  const days = H ? H.dates.length : 0;
  const weeks = Math.floor(days / 7);
  let h = `<div class="card" style="background:var(--amberbg);padding:12px 16px">
    <span class="chip sev3">not yet validated</span>
    <span style="font-size:12.5px;color:var(--amber)">These models have not been backtested, because backtesting needs realised outcomes and the tool has not been running long enough to have any. Nothing on this page should be read as evidence that one model outperforms another.</span></div>`;
  h += `<div class="kpis">${metric('real observation days', days)}${metric('complete weeks', weeks)}${metric('needed for a first backtest', VALID_MIN_WEEKS + ' weeks')}${metric('validation metrics available', weeks >= VALID_MIN_WEEKS ? 'yes' : 'no', weeks >= VALID_MIN_WEEKS ? 'var(--teal)' : 'var(--amber)')}</div>`;
  if (!H) {
    h += `<div class="card"><p style="font-size:13px;color:var(--ink2)">No score history file loaded. The daily pipeline appends to <code>data/history.json</code> on every run; history accumulates in git, which is what will eventually make a real backtest possible.</p></div>`;
    return h;
  }
  h += `<div class="card"><div class="lab">Real score history to date</div>
    <p style="font-size:13px;color:var(--ink2);margin:6px 0">Each series is the composite score for one risk, recorded once per pipeline run. This is the raw material a backtest needs; it is shown here so the accumulation is visible rather than asserted.</p>
    <div style="overflow-x:auto"><table class="t"><tr><th>Risk</th><th>First</th><th>Latest</th><th>Change</th><th>Distinct values</th></tr>` +
    Object.keys(H.scores).map(k => {
      const s = H.scores[k], a = s[0], b = s[s.length - 1], d = b - a;
      const r = RID(k);
      return `<tr><td>${r ? esc(r.title.split('—')[0].trim()) : esc(k)}</td><td>${a}</td><td>${b}</td>
        <td style="color:${d > 0 ? 'var(--red)' : d < 0 ? 'var(--teal)' : 'var(--ink3)'};font-weight:600">${d > 0 ? '+' : ''}${d}</td>
        <td>${new Set(s).size}</td></tr>`;
    }).join('') + `</table></div>
    <p class="meta" style="margin:8px 0 0">Risks whose distinct-value count is 1 have not moved because their inputs are curated rather than market-driven — that is expected, and it is also why they cannot contribute to a backtest.</p></div>`;
  h += `<div class="card"><div class="lab">What a real validation will report, once there is history</div>
    <ul style="font-size:12.5px;margin:6px 0;color:var(--ink2)">
      <li><b>Discrimination</b> — AUC on whether a high score preceded an actual limit breach or a materially adverse move.</li>
      <li><b>Calibration</b> — Brier score and a reliability curve; the forecast model's logistic needs Platt scaling against these outcomes before its output can be called a probability at all.</li>
      <li><b>Ranking</b> — top-decile hit rate, which is what a partner actually uses the score for.</li>
      <li><b>Drift</b> — recomputed weekly, with an alert on AUC movement beyond 0.05.</li>
    </ul>
    <p class="meta" style="margin:6px 0 0">Outcome definition has to be fixed in advance and written down, not chosen after the fact — otherwise the backtest measures the choice, not the model.</p></div>`;
  return h;
}
"""


def cut(src, pattern, what, flags=re.S):
    m = re.search(pattern, src, flags)
    assert m, f"NOT FOUND: {what}"
    return src[:m.start()] + src[m.end():]


def main():
    s = open(HTML, encoding="utf-8").read()
    n0 = len(s)

    # ---- 1. counterparty mock ------------------------------------------------
    s = cut(s, r'// ---- Lightweight counterparty risk module.*?\n(?=function secBreaches|function sec[A-Z]|// ----)', "counterparty module")
    s = s.replace("counterparty:secCounterparty, ", "")
    s = s.replace("counterparty:'Counterparty risk', ", "")
    for persona in ["'limits','breaches','scenario','concentration','counterparty','actions','outputs'",
                    "'exposure','limits','concentration','counterparty','breaches','evidence','outputs'",
                    "'breaches','limits','counterparty','watchlist','exposure','concentration','scenario','actions','outputs'",
                    "'exposure','concentration','scenario','movers','watchlist','counterparty','actions'"]:
        s = s.replace(persona, persona.replace("'counterparty',", ""))
    s = s.replace("exposure map, concentration, counterparty and breach queues",
                  "exposure map, concentration and breach queues")
    s = s.replace("FX / hedge / funding actions, counterparty limits, deadlines",
                  "FX / hedge / funding actions, limits, deadlines")

    # ---- 2. synthetic backtest ----------------------------------------------
    s = cut(s, r'// hseriesSynthetic remains ONLY for the backtest harness.*?\n(?=function |// ----|const )', "hseriesSynthetic")
    s = cut(s, r'// ---- Backtesting harness \(Phase 2\).*?\n(?=function backtestView)', "backtest harness")
    s = cut(s, r'function backtestView\(\)\{.*?\n(?=function |// ----|const )', "backtestView")
    s = s.replace("['backtest','Backtest']", "['validation','Validation']")
    s = s.replace("backtestView()", "validationView()")
    s = s.replace("MDLTAB==='backtest'", "MDLTAB==='validation'")
    s = s.replace("'backtest'", "'validation'")

    # ---- 3. structured-judgment family --------------------------------------
    s = cut(s, r'// Model 2 — Qualitative Structured Judgment.*?\n(?=// ---- Phase 2 math)', "mQualitative + AHPW")
    s = s.replace("const ENS_BASE={objective:0.15,qualitative:0.15,quant:0.20,tail:0.20,network:0.10,forecast:0.20};",
                  "// Weights sum to 1. The structured-judgment family was removed: it claimed an\n"
                  "// expert panel that did not exist and its ratings shared inputs with the\n"
                  "// objective model, so it added no independent information. Its 0.15 was\n"
                  "// redistributed to the two families that compute from real price series.\n"
                  "const ENS_BASE={objective:0.15,quant:0.25,tail:0.25,network:0.10,forecast:0.25};")
    s = re.sub(r'qualitative:[\d.]+,', '', s)
    s = s.replace("objective:mObjective(r),qualitative:mQualitative(r),quant,", "objective:mObjective(r),quant,")
    s = s.replace("['objective','Objective'],['qualitative','Qualitative'],", "['objective','Objective'],")
    s = cut(s, r"  const Q=models\.qualitative\.score_0_100.*?\n(?=  const sorted)", "judgment-led tag")
    s = s.replace("warnings,tag,breachProb", "warnings,tag:'',breachProb")
    s = cut(s, r"  if\(m\.tail\.score_0_100>=70 && m\.qualitative\.score_0_100<50\).*?\n", "tail-vs-judgment rule", 0)
    s = cut(s, r"  if\(m\.qualitative\.score_0_100>=70 && Math\.max\(.*?\n", "judgment-led rule", 0)
    s = cut(s, r" 'structured-judgment':\{read:.*?\n(?= '[a-z])", "structured-judgment doc")
    s = cut(s, r"  if\(rm\.criteria\) h\+=.*?\n", "AHP criteria table", 0)
    s = cut(s, r"  if\(rm\.FMEA_S!=null\) h\+=.*?\n", "FMEA component row", 0)
    s = s.replace("<tr><td>Structured judgment (AHP+FMEA+Bow-Tie)</td><td>qualitative</td><td>1.1</td>"
                  "<td>Consistency ratio &lt; 0.10; panel review pending</td><td>Expert panel lead</td><td>Quarterly</td></tr>", "")
    s = s.replace("<tr><td>Objective rules</td><td>objective</td><td>1.2</td><td>Backtest harness (mock outcomes)</td><td>Risk analytics</td><td>Quarterly</td></tr>",
                  "<tr><td>Objective rules</td><td>objective</td><td>1.2</td><td>Not yet validated — see Model lab → Validation</td><td>Risk analytics</td><td>Quarterly</td></tr>")
    s = re.sub(r"e\.tag==='judgment-led risk'\?'[^']*':e\.tag==='data-led risk'\?'[^']*':''", "''", s)

    # ---- 4. circular GPD fit -------------------------------------------------
    s = cut(s, r'function gpdFit\(losses\)\{.*?\n\}\n', "gpdFit")
    s = s.replace("function mTail(r,q,set){ const gpd=gpdFit(QCACHE[r.id]||[]);\n",
                  "function mTail(r,q,set){ const gpd=null; // EVT fit removed: fitting a GPD to the\n"
                  "  // simulator's own draws recovers the simulator's assumptions, not the market's\n"
                  "  // tails. A real peaks-over-threshold fit needs market return history.\n")
    s = s.replace("'EVT: GPD fitted by method-of-moments to MC exceedances above p90 (ξ clamped −0.4…0.45)'",
                  "'EVT: scaled Monte-Carlo tail ES. A real GPD peaks-over-threshold fit needs market return history and is not yet in place — the previous fit-to-simulation was circular and has been removed'")
    s = s.replace("'GPD fits simulated (not market-history) losses'",
                  "'No fitted extreme-value distribution yet — the tail is a scaled simulation output, not a measurement'")
    s = s.replace("'Copula: Gaussian, 800 joint draws, ρ from documented/live correlations (default 0.2, linked pairs 0.55)'",
                  "'Copula: Gaussian, 800 joint draws. ρ is the pipeline-computed Pearson correlation where overlapping price history exists; elsewhere a curated structural prior (0.55 for a documented linkage, 0.2 otherwise), which is a prior and not a measurement'")

    # ---- 5. Alpha Vantage key UX --------------------------------------------
    s = re.sub(r'<details style="margin-top:4px"><summary class="lab" style="cursor:pointer">Analyst option — connect a data key</summary>.*?</details>', '', s, flags=re.S)
    s = re.sub(r'<details style="margin-top:6px"><summary class="lab" style="cursor:pointer">Analyst override — compute from a personal Alpha Vantage key instead</summary>.*?</details>', '', s, flags=re.S)
    s = cut(s, r'window\.avSave = \(\) =>.*?\n', "avSave", 0)
    s = cut(s, r'window\.avForget = \(\) =>.*?\n', "avForget", 0)

    # ---- 6. probability language on an unfitted logistic --------------------
    s = s.replace("[['P(breach, 30d)',0.60*pB*100],['severity forecast',0.40*sevF]],",
                  "[['pressure index (30d)',0.60*pB*100],['severity forecast',0.40*sevF]],")
    s = s.replace("'S = 0.60 × P(breach 30d) + 0.40 × severity forecast.','Calibrated logistic: recentred slopes with a 3–90% clamp, so only near-certain in-force breaches approach the cap; Platt-scaling against realized outcomes is the backtest step.'",
                  "'S = 0.60 × pressure index + 0.40 × severity forecast.','The pressure index is a logistic transform of the score, velocity, tail and deadline proximity, clamped 3–90%. Its coefficients have never been fitted to realised outcomes, so it is a monotone ranking device and NOT a probability — do not quote it as one. Platt scaling against real outcomes is what would make it a probability; see Model lab → Validation.'")
    s = s.replace("'S = 0.60 × P(breach 30d) + 0.40 × severity forecast'",
                  "'S = 0.60 × pressure index + 0.40 × severity forecast'")
    s = s.replace("read:'The forward view: probability this becomes a breach event inside 30 days.'",
                  "read:'The forward view: a ranked 30-day pressure index. Not a calibrated probability — the coefficients have never been fitted to outcomes.'")
    s = s.replace("'Probability clamped 3–90%'", "'Index clamped 3–90%; it is a ranking, not a probability'")
    s = s.replace("'Coefficients seeded, not fitted — see the Backtest tab for the validation harness'",
                  "'Coefficients seeded, never fitted — so this is a ranking device, not a probability. See Model lab → Validation'")
    s = s.replace("metric('P(breach 30d)',Math.round(e.breachProb*100)+'%'", "metric('pressure index 30d',Math.round(e.breachProb*100)")
    s = s.replace("' · P(breach 30d) '+Math.round(res.ensemble.breachProb*100)+'%'", "' · pressure index '+Math.round(res.ensemble.breachProb*100)")
    s = s.replace("why:'Objective and ensemble high with breach probability above 50% — escalate now.'",
                  "why:'Objective and ensemble both high with the pressure index above 50 — escalate now.'")
    s = s.replace("{breachProb30d:Math.round(pB*100)/100,", "{pressureIndex30d:Math.round(pB*100)/100,breachProb30d:Math.round(pB*100)/100,")

    # ---- 7. dead placeholder -------------------------------------------------
    s = s.replace('{"__placeholder": "The run-cycle playbook replaces the two JSON script blocks below on each regeneration."}\n', "")

    open(HTML, "w", encoding="utf-8").write(s)

    # inject the validation panel next to the other model views
    s = open(HTML, encoding="utf-8").read()
    s = s.replace("function ensembleView(res){", VALIDATION_JS.strip() + "\n\nfunction ensembleView(res){", 1)
    open(HTML, "w", encoding="utf-8").write(s)
    print(f"removals applied: {n0} -> {len(s)} chars ({n0 - len(s)} removed net of the validation panel)")


if __name__ == "__main__":
    main()
